# Generated by Django 5.1.6 on 2025-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='item_zips'),
        ),
    ]
